# Generated by Django 2.2.16 on 2020-10-05 16:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('consultas', '0002_auto_20201003_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consultas_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
