# Generated by Django 2.2.16 on 2020-10-03 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendas', '0002_auto_20201003_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horarios',
            name='horario',
            field=models.TimeField(unique=True),
        ),
    ]
